# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-algorithms" = "sha256-cJfOxBB74V7ZE4g6OehYIdtmqYnSFIkJLpkxPo9jiUo=";
    "swift-argument-parser" = "sha256-90ECc3iEmxvOUk9iLKbQdQEz88dOisPqWsJLOFcKUV8=";
    "swift-log" = "sha256-atKC2xMHxtjPpeh7JepWptHCB1Pvcn2PNvc7qjTgjYU=";
    "swift-numerics" = "sha256-bRkiRuxb4O3SmpsGZ5YaUR4cV3IQoES+u3xZTCzaQ+c=";
  };
}
